run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - misspell
    - revive
    - gocyclo
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - paramTypeCombine
      - unnamedResult
  revive:
    rules:
      - name: var-naming
        disabled: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gocritic
    # Exclude mock files
    - path: mock\.go
      linters:
        - unused
        - deadcode
  max-same-issues: 0
  max-issues-per-linter: 0
